### ISSUE TITLE
Training from scratch pytorch

### ISSUE THREAD

**Issue by chowwil** [TIBHannover/GeoEstimation#12]
Hi, Is there another way to train from scratch without using the flickr images or having to download images?
Say using your own set of images on your machine and possibly without shards?

I'm unable to download the flickr images. And would like to train on a smaller subset.
And trying to convert my small dataset of images into message packs causes me to run into issues trying to alter the code. 

Thank you.

**Comment by jtheiner** [comment]
Our implementation only writes a set of images and respective IDs in a msgpack format (see msgpack_viewer.py) given a list of image URLs.
The simplest way would be to write your own ImageDataLoader class that takes, for instance, an image folder instead of URLs (https://github.com/TIBHannover/GeoEstimation/blob/master/download_images.py#L185).
This would allow you to convert local files to msgpack without having to modify other (training) code.

**Comment by jtheiner** [comment]
Regarding your second issue "I'm unable to download the flickr images":
I checked this for the first 10k URLs of the MP-16 dataset and it turns out, that around 90% are available. Perhaps, you are just irritated from logging all non-available images (404, 410 error codes).

**Comment by chowwil** [comment]
got it to work eventually 👍  rewrote the imageDataLoader class as well as download_url function.
