### ISSUE TITLE
code can't work

### ISSUE THREAD

**Issue by fzweclipse** [TIBHannover/GeoEstimation#15]
I use pytorch1.10.0, I can't run the code.
train_base.py line21,
self.hparam = hparams

torch.nn.nodules.nodule.py

error： in __setattr__
object.__setattr__(self,name,value)
AttributeError: Can't set attribute.

**Comment by TIB-Visual-Analytics** [comment]
Hi, we are using PyTorch 1.6 in our project. Please make sure that you use the correct versions of the libraries as indicated in the [environment.yml](https://github.com/TIBHannover/GeoEstimation/blob/master/environment.yml).

You can also use anaconda as described in the [instructions](https://github.com/TIBHannover/GeoEstimation/tree/master#Requirements) to run the code.

**Comment by turicumoperarius** [comment]
I encountered the same problem today. Because I wanted to run the code on more current versions of the dependencies I did have a small look into the "setattr" error. Its actually pretty simple to resolve, at least for inference.

Just replace the following line of code in classification/train_base.py in the "__init__" method of the MultiPartitioningClassifier Class and you should be good to go.

`
self.hparams = hparams
**... to ...**
for key in hparams.keys():
         self.hparams[key]=hparams[key]
`
