### ISSUE TITLE
Can I train on my own dataset and locations?

### ISSUE THREAD

**Issue by jyjyj** [TIBHannover/GeoEstimation#5]
As expressed in the title, I would like to retrain to get more specific lat-long coordinates on my own dataset (am interested in a smaller geographical area). Would appreciate some help on how to do this if possible, thanks!

**Comment by TIB-Visual-Analytics** [comment]
We are currently working on a script that you could use to train a customized model. In this regard, we are planning to update the code to tensorflow 2.1. I hope we are able to commit something in the few next days. If you want to try yourself in the meantime you basically have to do the following steps:

1. Create a cell partitioning using the s2 library. This allows you to train the model as classification approach since you can assign an image to a geographical cell based on the GPS coordinate
2. Train the network using tensorflow, pytorch or whatever you want. There are several tutorials how to do that, e.g., 
- https://keras.io/applications/
- https://pytorch.org/tutorials/beginner/finetuning_torchvision_models_tutorial.html

**Comment by jyjyj** [comment]
Hi, thanks! Please keep me informed when you commit the customised training code :) In the meantime, I will try and explore training the network as I am not very familiar with retraining ML models. 

Just to confirm as well, would the custom training only be doable in TF as the models are tensorflow checkpoints?

**Comment by TIB-Visual-Analytics** [comment]
We have added a new branch "tf2" that allows training using recent TensorFlow versions.
